### ISSUE TITLE
Old version on `ansible-galaxy`

### ISSUE THREAD

**Issue by dorkamotorka** [ansible-collections/cloud.terraform#36]
##### SUMMARY

In `ansible-galaxy` terraform module is still on a `1.0.0` version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

None

##### ANSIBLE VERSION

```
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```p
# /home/ubuntu/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
cloud.terraform 1.0.0  
```

##### CONFIGURATION

```
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

`Linux Ubuntu 22.04`

##### STEPS TO REPRODUCE
Run `ansible-galaxy collection install cloud.terraform` and check which version it installs.

##### EXPECTED RESULTS

At the moment, I expected to install version `1.0.1`.

##### ACTUAL RESULTS
It installs version `1.0.0`

**Comment by dorkamotorka** [comment]
I suggest creating a GitHub Action that automates the release to the Ansible Galaxy. I can develop it, but I don't have enough rights to test it properly.

**Comment by tima** [comment]
Thanks for pointing this out @dorkamotorka.

As I recall (@abikouo correct me if I'm wrong) there was a problem with the 1.0.0 build metadata that the Automation Hub didn't like. The 1.0.0 version was already in and locked that version number so the version number had to be incremented in order to publish it there. There is no functional difference between 1.0.0 and 1.0.1. I understand why that was confusing especially since the change log was somehow not filled out. I'm going to open a ticket for that now.
