### ISSUE TITLE
Remote State Support

### ISSUE THREAD

**Issue by kominoshja** [ansible-collections/cloud.terraform#65]
##### SUMMARY
Using remote states allow better usage in teams (locking) and allow integration with tools like gitlab

##### ISSUE TYPE
- Feature Idea

**Comment by tima** [comment]
I agree @kominoshja. This collection already supports this. We test on S3, azurerm and gcs, but any remote backend should work.

**Comment by Gaurav2Github** [comment]
how about state stored in terraform cloud workspace?

**Comment by robotski** [comment]
For anyone else who finds themselves very confused as to why inventory with a remote statefile doesn't work, it's because the feature was only added in https://github.com/ansible-collections/cloud.terraform/commit/8ab8757bc5950a500ae30743b794a0ee14472f5c and the latest release is before then. (as of this writing)

As a workaround until there's a new release, what I did was:

`rm -r ~/.ansible/collections/ansible_collections/cloud/terraform*`

then from inside the `cloud` directory, clone this repo and rename it to `terraform`.
